---
title: "roundrobin package"
author: by kilometer
output: 
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=F}
library(tidyverse)
roundrobin <- function(df, key, combination = FALSE){
  grid <-
    mygrid(df, {{ key }}, combination = combination)

  df_nest <-
    mynest(df, {{ key }})

  df_rr <-
    grid %>%
    dplyr::left_join(
      df_nest %>% dplyr::rename(Var1 = key),
      by = "Var1"
    ) %>%
    rename(data_Var1 = data) %>%
    dplyr::left_join(
      df_nest %>% dplyr::rename(Var2 = key),
      by = "Var2"
    ) %>%
    dplyr::rename(data_Var2 = data)

  return(df_rr)
}

mynest <- function(df, key){
  df %>%
    dplyr::rename(key := {{ key }}) %>%
    dplyr::group_nest(key)
}

mygrid <- function(df, key, combination = FALSE){
  df_nest <-
    mynest(df, key = {{ key }})

  grid <-
    df_nest$key %>%
    base::expand.grid(Var1 = ., Var2 = .)

  if(combination == TRUE){
    grid <-
      grid %>%
      base::subset(base::unclass(Var1) < base::unclass(Var2))
  }

  grid %>%
    tibble::as_tibble() %>%
    return()
}
```

## Install

from github

```{r eval=FALSE}
devtools::install_github("kilometer0101/roundrobin")
```

## Useage

```{r, eval=FALSE}
library(roundrobin)
```

### Sample data

```{r}
str(InsectSprays)
dplyr::group_nest(InsectSprays, spray)
```

### Use roundrobin function

- roundrobin

```{r}
roundrobin(InsectSprays, key = spray)
```

- combination

```{r}
roundrobin(
  InsectSprays, key = spray, combination = TRUE
  )
```
